In [1]:
import numpy as np

### numpy.bincount(x, weights=None, minlength=0)
- 计算非负int数组中每个值的出现次数。

- 容器的数量（大小为1）比x中的最大值大1。 如果指定了minlength，则输出数组中至少会有minlength的bin. 每个bin都以x表示其索引值的出现次数。 如果指定权重，则输入数组由它加权，即如果在位置i处找到值n，则out[n] + = weight [i]而不是out [n] + = 1。

参数：
- x：输入数组
- weights：加权数组，与x的shape相同
- minlength：输出矩阵bin数的最小值

返回：
- out : 输入矩阵分bin的结果。输出矩阵长度：输入矩阵最大值+1 = np.amax(x)+1

### example1:统计每个元素出现次数

In [2]:
a=np.arange(8)
a

array([0, 1, 2, 3, 4, 5, 6, 7])

In [4]:
b=np.bincount(a)
b

array([1, 1, 1, 1, 1, 1, 1, 1], dtype=int64)

### example2:输出数组长度

In [9]:
x = np.array([0, 1, 1, 3, 2, 1, 7, 23])
b=np.bincount(x)
print(b.size)
print(b)
assert b.size == np.amax(x)+1

24
[1 3 1 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]


### example3:输入数据类型要为整数

In [10]:
np.bincount(np.arange(5, dtype=float))

TypeError: Cannot cast array data from dtype('float64') to dtype('int64') according to the rule 'safe'

### example4:有权值w，则计算输出时，累加x值对应位置的w值

In [11]:
w = np.array([0.3, 0.5, 0.2, 0.7, 1., -0.6])
x = np.array([0, 1, 1, 2, 2, 2])
y1= np.bincount(x)
y2= np.bincount(x,w)
print(y1)
print(y2)

[1 2 3]
[0.3 0.7 1.1]
