In [1]:
import numpy as np

In [17]:
#x,y,z轴坐标范围=0:3,0:3,0:3
a=np.mgrid[0:3,0:3,0:3]
print(a.shape)
print(a)
#获取网格中所有坐标点位置
x=a.reshape(3,-1)
y=x.T
print(y)

(3, 3, 3, 3)
[[[[0 0 0]
   [0 0 0]
   [0 0 0]]

  [[1 1 1]
   [1 1 1]
   [1 1 1]]

  [[2 2 2]
   [2 2 2]
   [2 2 2]]]


 [[[0 0 0]
   [1 1 1]
   [2 2 2]]

  [[0 0 0]
   [1 1 1]
   [2 2 2]]

  [[0 0 0]
   [1 1 1]
   [2 2 2]]]


 [[[0 1 2]
   [0 1 2]
   [0 1 2]]

  [[0 1 2]
   [0 1 2]
   [0 1 2]]

  [[0 1 2]
   [0 1 2]
   [0 1 2]]]]
[[0 0 0]
 [0 0 1]
 [0 0 2]
 [0 1 0]
 [0 1 1]
 [0 1 2]
 [0 2 0]
 [0 2 1]
 [0 2 2]
 [1 0 0]
 [1 0 1]
 [1 0 2]
 [1 1 0]
 [1 1 1]
 [1 1 2]
 [1 2 0]
 [1 2 1]
 [1 2 2]
 [2 0 0]
 [2 0 1]
 [2 0 2]
 [2 1 0]
 [2 1 1]
 [2 1 2]
 [2 2 0]
 [2 2 1]
 [2 2 2]]


In [10]:
start=np.array((-12,-12,52))
stop=np.array((144,144,144))+start
step=np.array((64,64,64))
b=np.mgrid[start[0]:stop[0]:step[0], start[1]:stop[1]:step[1],
                               start[2]:stop[2]:step[2]]

In [11]:
print(b.shape)
print(b)

(3, 3, 3, 3)
[[[[-12 -12 -12]
   [-12 -12 -12]
   [-12 -12 -12]]

  [[ 52  52  52]
   [ 52  52  52]
   [ 52  52  52]]

  [[116 116 116]
   [116 116 116]
   [116 116 116]]]


 [[[-12 -12 -12]
   [ 52  52  52]
   [116 116 116]]

  [[-12 -12 -12]
   [ 52  52  52]
   [116 116 116]]

  [[-12 -12 -12]
   [ 52  52  52]
   [116 116 116]]]


 [[[ 52 116 180]
   [ 52 116 180]
   [ 52 116 180]]

  [[ 52 116 180]
   [ 52 116 180]
   [ 52 116 180]]

  [[ 52 116 180]
   [ 52 116 180]
   [ 52 116 180]]]]


In [14]:
c=b.reshape(3,-1)#每行的值分别为x/y/z轴索引取值
d=c.T#转置后，每行为1个坐标位置
print(c.shape)
print(c)
print(d.shape)
print(d)

(3, 27)
[[-12 -12 -12 -12 -12 -12 -12 -12 -12  52  52  52  52  52  52  52  52  52
  116 116 116 116 116 116 116 116 116]
 [-12 -12 -12  52  52  52 116 116 116 -12 -12 -12  52  52  52 116 116 116
  -12 -12 -12  52  52  52 116 116 116]
 [ 52 116 180  52 116 180  52 116 180  52 116 180  52 116 180  52 116 180
   52 116 180  52 116 180  52 116 180]]
(27, 3)
[[-12 -12  52]
 [-12 -12 116]
 [-12 -12 180]
 [-12  52  52]
 [-12  52 116]
 [-12  52 180]
 [-12 116  52]
 [-12 116 116]
 [-12 116 180]
 [ 52 -12  52]
 [ 52 -12 116]
 [ 52 -12 180]
 [ 52  52  52]
 [ 52  52 116]
 [ 52  52 180]
 [ 52 116  52]
 [ 52 116 116]
 [ 52 116 180]
 [116 -12  52]
 [116 -12 116]
 [116 -12 180]
 [116  52  52]
 [116  52 116]
 [116  52 180]
 [116 116  52]
 [116 116 116]
 [116 116 180]]
