## numpy.random.permutation
### permutation(x)
- 随机置换序列，或返回置换范围
- **当x是多维数组时，它只是沿着它的第一个索引打乱**
- 参数：如果x是整数，则随机置换np.arange（x）。如果x是一个数组，则复制并随机地移动元素。
- 返回：ndarray

In [1]:
import numpy as np

In [3]:
a=np.random.permutation(10)
print(a)

[1 6 9 8 0 4 3 2 7 5]


In [28]:
arr=np.arange(9).reshape((3,3))
arr_permuted=np.random.permutation(arr)
print(arr_permuted)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
