In [1]:
import numpy as np

In [5]:
a=np.array([2,23,4],dtype=np.float)

In [6]:
#与list相比中间没有逗号
print(a)
print(a.dtype)

[ 2. 23.  4.]
float64


In [8]:
#定义全0的矩阵，默认dtype=np.float64
b=np.zeros((3,4))
#定义全1的矩阵
c=np.ones((5,6))
print(b.dtype)
print(c)

float64
[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [10]:
#根据范围和步长指定生成的数组
d=np.arange(1,20,2)
print(d)
#改变shape
e=d.reshape((2,5))
print(e)

[ 1  3  5  7  9 11 13 15 17 19]
[[ 1  3  5  7  9]
 [11 13 15 17 19]]


In [11]:
#根据范围和数量指定生成的数组
f=np.linspace(1,10,20)
print(f)

[ 1.          1.47368421  1.94736842  2.42105263  2.89473684  3.36842105
  3.84210526  4.31578947  4.78947368  5.26315789  5.73684211  6.21052632
  6.68421053  7.15789474  7.63157895  8.10526316  8.57894737  9.05263158
  9.52631579 10.        ]
