In [1]:
import numpy as np

In [2]:
#一维数组
a=np.array([2,5,9,6])
b=np.arange(4)

In [4]:
c=a+b
print(c)
#次方
d=a**2
print(d)

[ 2  6 11  9]
[ 4 25 81 36]


In [6]:
#三角函数sin,cos,tan弧度制
e=10*np.sin(a)
print(e)

[ 9.09297427 -9.58924275  4.12118485 -2.79415498]


In [7]:
print(a<6)

[ True  True False False]


In [9]:
#多维矩阵
x=a.reshape((2,2))
y=b.reshape((2,2))
print(x)
print(y)

[[2 5]
 [9 6]]
[[0 1]
 [2 3]]


In [12]:
#矩阵元素乘
z=x*y
print(z)
#矩阵乘法np.dot
z_dot=np.dot(x,y)
z_dot2=x.dot(y)
print(z_dot)
print(z_dot2)

[[ 0  5]
 [18 18]]
[[10 17]
 [12 27]]
[[10 17]
 [12 27]]


In [16]:
s=np.random.random((2,4))
print(s)
print('求和',np.sum(s))
print('最小值',np.min(s))
print('最大值',np.max(s))
#指定维度axis
#axis=0:对每一列所有行计算
#axis=1：对每一行所有列计算
print(np.sum(s,axis=0))
print(np.sum(s,axis=1))

[[0.02316251 0.16489228 0.6117318  0.73682831]
 [0.48227794 0.68170897 0.73913023 0.70292185]]
求和 4.142653892115857
最小值 0.023162505340168282
最大值 0.7391302339386169
[0.50544045 0.84660125 1.35086203 1.43975016]
[1.5366149 2.606039 ]
