In [1]:
import numpy as np

In [2]:
A=np.arange(0,16).reshape((2,8))

In [8]:
#获取最小元素位置
print(np.argmin(A))
print(np.argmax(A))
#平均值
print(np.mean(A))
#中位数
print(np.median(A))
#逐个与前面的值累加:cumsum
print(np.cumsum(A))
#累差:与前一个值的差
print(np.diff(A))

0
15
7.5
7.5
[  0   1   3   6  10  15  21  28  36  45  55  66  78  91 105 120]
[[1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]]


In [12]:
#逐行排序
B=np.arange(16,0,-1).reshape((2,8))
print(B)
print(np.sort(B))
#转置
print(np.transpose(B))
print(B.T)

[[16 15 14 13 12 11 10  9]
 [ 8  7  6  5  4  3  2  1]]
[[ 9 10 11 12 13 14 15 16]
 [ 1  2  3  4  5  6  7  8]]
[[16  8]
 [15  7]
 [14  6]
 [13  5]
 [12  4]
 [11  3]
 [10  2]
 [ 9  1]]
[[16  8]
 [15  7]
 [14  6]
 [13  5]
 [12  4]
 [11  3]
 [10  2]
 [ 9  1]]


In [13]:
#根据指定最小值和最大值截取矩阵
#小于最小值==>最小值
#大于最大值==>最大值
print(np.clip(A,5,9))

[[5 5 5 5 5 5 6 7]
 [8 9 9 9 9 9 9 9]]
