In [1]:
import numpy as np

In [4]:
A=np.arange(12).reshape((3,4))
print(A)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [8]:
#2指定后的数量，axis指定在哪一维度上split
B=np.split(A,3,axis=0)
print(B)

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]


In [9]:
#不等分割
C=np.array_split(A,3,axis=1)
print()